export interface I130Question {
  id: string;
  part: string;
  partTitle: string;
  label: string;
  question: string;
  hint: string;
  optional?: boolean;
  options?: string[];
}

export const I130_QUESTIONS: I130Question[] = [
  // ── Part 1: Relationship ───────────────────────────────────────────────────
  {
    id: "relationship_type",
    part: "Part 1",
    partTitle: "Relationship",
    label: "Relationship to Beneficiary",
    question:
      "Welcome! Let's fill out Form I-130 together — this petition establishes your qualifying family relationship with the relative you want to sponsor for a green card.\n\nFirst, what is your relationship to the person you're petitioning for (the beneficiary)?",
    hint: "Select one",
    options: [
      "Spouse",
      "Parent (I am the child, petitioning for my parent)",
      "Child (I am the parent, petitioning for my child)",
      "Brother/Sister",
      "Stepparent/Stepchild",
      "Parent of an Adopted Child / Adopted Child",
    ],
  },
  {
    id: "relationship_how_created",
    part: "Part 1",
    partTitle: "Relationship",
    label: "How the Relationship Was Created",
    question: "How was this relationship created? For example: birth, marriage, adoption, or a step-relationship through a parent's marriage.",
    hint: "e.g., Birth, Marriage, Adoption",
  },
  {
    id: "mail_order_bride",
    part: "Part 1",
    partTitle: "Relationship",
    label: "Met Through International Marriage Broker?",
    question: "If your relationship is a marriage — did you and your spouse meet through the services of an international marriage broker (sometimes called a \"mail-order bride\" service)? Type 'N/A' if this isn't a marriage-based petition.",
    hint: "Yes, No, or N/A",
    optional: true,
    options: ["Yes", "No", "N/A"],
  },
  {
    id: "related_by_blood",
    part: "Part 1",
    partTitle: "Relationship",
    label: "Also Related by Blood?",
    question: "Aside from the relationship above, are you and the beneficiary also related by blood (for example, cousins who later married)?",
    hint: "Select one",
    options: ["Yes", "No"],
  },

  // ── Part 2: Information About You (Petitioner) ────────────────────────────
  {
    id: "petitioner_family_name",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's Family Name (Last Name)",
    question: "Now let's cover your information as the petitioner.\n\nWhat is your family name (last name)?",
    hint: "e.g., Garcia",
  },
  {
    id: "petitioner_given_name",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's Given Name (First Name)",
    question: "What is your given name (first name)?",
    hint: "e.g., Maria",
  },
  {
    id: "petitioner_middle_name",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's Middle Name",
    question: "What is your middle name? (Type 'N/A' if you don't have one)",
    hint: "e.g., Elena or N/A",
    optional: true,
  },
  {
    id: "petitioner_other_names",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Other Names Used",
    question: "Have you used any other names (maiden name, nicknames, aliases)? List them, or type 'N/A' if none.",
    hint: "e.g., Maria Lopez (maiden name) or N/A",
    optional: true,
  },
  {
    id: "petitioner_a_number",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's A-Number / USCIS Online Account Number",
    question: "Do you have an Alien Registration Number (A-Number) or a USCIS Online Account Number? Provide whichever you have, or type 'N/A' if neither applies.",
    hint: "e.g., A-123456789 or N/A",
    optional: true,
  },
  {
    id: "petitioner_ssn",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's U.S. Social Security Number",
    question: "What is your U.S. Social Security Number?",
    hint: "XXX-XX-XXXX",
  },
  {
    id: "petitioner_dob",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's Date of Birth",
    question: "What is your date of birth?",
    hint: "MM/DD/YYYY",
  },
  {
    id: "petitioner_place_of_birth",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's City and Country of Birth",
    question: "What city and country were you born in?",
    hint: "e.g., Mumbai, India",
  },
  {
    id: "petitioner_citizenship_basis",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Basis for U.S. Citizenship or LPR Status",
    question: "How did you obtain your current U.S. citizenship or lawful permanent resident status? If naturalized, mention your certificate number and the place/date it was issued.",
    hint: "Select one",
    options: [
      "Birth in the United States",
      "Naturalization",
      "Acquired/Derived Through Parents (Citizen)",
      "Lawful Permanent Resident (Green Card holder)",
    ],
  },
  {
    id: "petitioner_marital_status",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's Current Marital Status",
    question: "What is your current marital status?",
    hint: "Select one",
    options: ["Single, Never Married", "Married", "Divorced", "Widowed", "Marriage Annulled", "Separated"],
  },
  {
    id: "petitioner_mailing_street",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Mailing Address – Street Number and Name",
    question: "What is your current mailing address — street number and name? Include apartment/suite number if applicable.",
    hint: "e.g., 456 Oak Avenue Apt 2",
  },
  {
    id: "petitioner_mailing_city_state_zip",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Mailing Address – City, State, and ZIP Code",
    question: "What city, state, and ZIP code?",
    hint: "e.g., Phoenix, AZ 85001",
  },
  {
    id: "petitioner_address_history_5yr",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Physical Address History (Last 5 Years)",
    question: "List every place you've lived over the last 5 years, with dates for each (city, state, country, and from/to dates). If your current address is the only one, just say so.",
    hint: "e.g., Phoenix AZ, 2019–present; Denver CO, 2016–2019",
  },
  {
    id: "petitioner_employment_history_5yr",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Employment History (Last 5 Years)",
    question: "List your employers over the last 5 years, with job title, city/state, and from/to dates for each.",
    hint: "e.g., Acme Corp, Software Engineer, Phoenix AZ, 2021–present",
  },
  {
    id: "petitioner_daytime_phone",
    part: "Part 2",
    partTitle: "Information About You (Petitioner)",
    label: "Petitioner's Daytime Telephone Number and Email",
    question: "What is your daytime telephone number, and your email address (type 'N/A' for the email if you don't have one)?",
    hint: "e.g., (602) 555-1234, maria@email.com",
  },

  // ── Part 4: Information About Beneficiary ─────────────────────────────────
  {
    id: "beneficiary_family_name",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Family Name (Last Name)",
    question: "Now let's cover information about the relative you're petitioning for (the beneficiary).\n\nWhat is their family name (last name)?",
    hint: "e.g., Garcia",
  },
  {
    id: "beneficiary_given_name",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Given Name (First Name)",
    question: "What is their given name (first name)?",
    hint: "e.g., Carlos",
  },
  {
    id: "beneficiary_middle_name",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Middle Name",
    question: "What is their middle name? (Type 'N/A' if none)",
    hint: "e.g., Andres or N/A",
    optional: true,
  },
  {
    id: "beneficiary_other_names",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Other Names Used",
    question: "Has the beneficiary used any other names (maiden name, nicknames, aliases)? List them, or type 'N/A' if none.",
    hint: "e.g., Carlos Reyes or N/A",
    optional: true,
  },
  {
    id: "beneficiary_identifiers",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's A-Number, USCIS Online Account Number, or SSN",
    question: "Does the beneficiary have an Alien Registration Number (A-Number), a USCIS Online Account Number, or a U.S. Social Security Number? List whichever apply, or type 'N/A' if none.",
    hint: "e.g., A-987654321 or N/A",
    optional: true,
  },
  {
    id: "beneficiary_dob",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Date of Birth",
    question: "What is the beneficiary's date of birth?",
    hint: "MM/DD/YYYY",
  },
  {
    id: "beneficiary_place_of_birth",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's City and Country of Birth",
    question: "What city and country was the beneficiary born in?",
    hint: "e.g., Guadalajara, Mexico",
  },
  {
    id: "beneficiary_current_address",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Current Address",
    question: "What is the beneficiary's current address — whether abroad or in the U.S.? Include street, city, state/province, country, and postal code.",
    hint: "e.g., Calle Reforma 12, Guadalajara, Jalisco, Mexico",
  },
  {
    id: "beneficiary_marital_status",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Current Marital Status",
    question: "What is the beneficiary's current marital status?",
    hint: "Select one",
    options: ["Single, Never Married", "Married", "Divorced", "Widowed", "Marriage Annulled", "Separated"],
  },
  {
    id: "beneficiary_marriage_and_spouse",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Marriage History & Current Spouse",
    question: "If the beneficiary is currently married, what is their spouse's full name? Also list any prior marriages and how each ended (divorce, death, annulment) with dates. Type 'N/A' if never married.",
    hint: "e.g., Current spouse Ana Reyes; prior marriage to Elena Cruz, divorced 2018",
    optional: true,
  },
  {
    id: "beneficiary_parents_names",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Parents' Names",
    question: "What are the full names of the beneficiary's mother and father?",
    hint: "e.g., Jose Garcia (father), Rosa Garcia (mother)",
  },
  {
    id: "beneficiary_in_us",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Is Beneficiary Currently in the United States?",
    question: "Is the beneficiary currently in the United States?",
    hint: "Select one",
    options: ["Yes", "No"],
  },
  {
    id: "beneficiary_immigration_status_i94",
    part: "Part 4",
    partTitle: "Information About Beneficiary",
    label: "Beneficiary's Current Immigration Status & I-94 Info (if in U.S.)",
    question: "If the beneficiary is in the U.S., what is their current immigration status (e.g., visitor, student, out of status), and what is their I-94 Arrival/Departure number and expiration date? Type 'N/A' if the beneficiary is abroad.",
    hint: "e.g., F-1 student, I-94 #12345678901, expires 12/01/2026 or N/A",
    optional: true,
  },

  // ── Part 5: Other Information ─────────────────────────────────────────────
  {
    id: "petitioner_filed_before",
    part: "Part 5",
    partTitle: "Other Information",
    label: "Filed a Petition for This or Any Other Relative Before?",
    question: "Have you ever filed a petition for this beneficiary, or for any other relative, before? If yes, briefly describe who and the outcome. Type 'No' if this is your first petition.",
    hint: "e.g., No, or 'Yes — filed for spouse in 2019, approved'",
  },
  {
    id: "concurrent_petitions",
    part: "Part 5",
    partTitle: "Other Information",
    label: "Filing Other Petitions at the Same Time?",
    question: "Are you submitting any other Form I-130 petitions for other relatives at the same time as this one? If yes, list who. Type 'No' if this is the only petition you're filing right now.",
    hint: "e.g., No, or 'Yes — also filing for my daughter'",
    optional: true,
  },
];

export const I130_PARTS = [
  { id: "Part 1", title: "Relationship" },
  { id: "Part 2", title: "Information About You (Petitioner)" },
  { id: "Part 4", title: "Information About Beneficiary" },
  { id: "Part 5", title: "Other Information" },
];
