export interface I140Question {
  id: string;
  part: string;
  partTitle: string;
  label: string;
  question: string;
  hint: string;
  optional?: boolean;
  options?: string[];
}

export const I140_QUESTIONS: I140Question[] = [
  // ── Part 1: Petitioner/Employer Information ───────────────────────────────
  {
    id: "employer_is_self_petitioner",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Petitioner Type",
    question:
      "Welcome! Let's fill out Form I-140 together.\n\nFirst — is this petition being filed by an employer sponsoring a worker, or are you self-petitioning (common for EB-1A extraordinary ability or EB-2 National Interest Waiver)?",
    hint: "Select one",
    options: ["Employer is filing (sponsoring me)", "I am self-petitioning"],
  },
  {
    id: "employer_name",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Petitioner / Company Name",
    question: "What is the petitioner's name? If an employer is filing, give the company's legal name. If you're self-petitioning, give your own full name.",
    hint: "e.g., Acme Technologies Inc.",
  },
  {
    id: "employer_fein",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Federal Employer Identification Number (FEIN)",
    question: "What is the petitioner's Federal Employer Identification Number (FEIN)? Type 'N/A' if there isn't one (e.g., an individual self-petitioner).",
    hint: "e.g., 12-3456789 or N/A",
    optional: true,
  },
  {
    id: "employer_type_of_business",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Type of Business",
    question: "What type of business is the petitioner? (Industry or nature of the business — e.g., 'Software Development', 'Hospital', 'Restaurant'.)",
    hint: "e.g., Software Development",
  },
  {
    id: "employer_date_established",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Year Established",
    question: "What year was the business established?",
    hint: "e.g., 2010",
  },
  {
    id: "employer_current_employees",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Current Number of Employees",
    question: "How many employees does the petitioner currently have?",
    hint: "e.g., 250",
  },
  {
    id: "employer_gross_annual_income",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Gross and Net Annual Income",
    question: "What is the petitioner's gross annual income (most recent tax year)? Also include net annual income if you have it.",
    hint: "e.g., $5,000,000 gross, $750,000 net",
  },
  {
    id: "employer_address",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Petitioner's Address",
    question: "What is the petitioner's full address? Include street, suite/unit, city, state, and ZIP code.",
    hint: "e.g., 1 Infinite Loop Suite 100, Cupertino, CA 95014",
  },
  {
    id: "employer_contact_phone",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Petitioner's Daytime Phone Number",
    question: "What is the petitioner's daytime telephone number?",
    hint: "e.g., (408) 555-1234",
  },
  {
    id: "employer_contact_email",
    part: "Part 1",
    partTitle: "Information About the Petitioner",
    label: "Petitioner's Email Address",
    question: "What is the petitioner's email address? Type 'N/A' if none.",
    hint: "e.g., hr@acme.com or N/A",
    optional: true,
  },

  // ── Part 2: Petition Type ──────────────────────────────────────────────────
  {
    id: "classification_requested",
    part: "Part 2",
    partTitle: "Petition Type",
    label: "Classification Requested",
    question: "Which employment-based immigrant classification is being requested?",
    hint: "Select one",
    options: [
      "EB-1A — Alien of extraordinary ability",
      "EB-1B — Outstanding professor or researcher",
      "EB-1C — Multinational executive or manager",
      "EB-2 — Advanced degree professional",
      "EB-2 NIW — National interest waiver",
      "EB-3 — Skilled worker",
      "EB-3 — Professional",
      "EB-3 — Other worker",
    ],
  },

  // ── Part 3: Information About the Beneficiary ─────────────────────────────
  {
    id: "beneficiary_family_name",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Family Name (Last Name)",
    question: "Now let's fill in information about the beneficiary — the worker being sponsored.\n\nWhat is the beneficiary's family name (last name)?",
    hint: "e.g., Sharma",
  },
  {
    id: "beneficiary_given_name",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Given Name (First Name)",
    question: "What is the beneficiary's given name (first name)?",
    hint: "e.g., Ravi",
  },
  {
    id: "beneficiary_middle_name",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Middle Name",
    question: "What is the beneficiary's middle name? Type 'N/A' if none.",
    hint: "e.g., Kumar or N/A",
    optional: true,
  },
  {
    id: "beneficiary_dob",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Date of Birth",
    question: "What is the beneficiary's date of birth?",
    hint: "MM/DD/YYYY",
  },
  {
    id: "beneficiary_country_of_birth",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Country of Birth",
    question: "What country was the beneficiary born in?",
    hint: "e.g., India",
  },
  {
    id: "beneficiary_country_of_citizenship",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Country of Citizenship",
    question: "What is the beneficiary's country of citizenship or nationality?",
    hint: "e.g., India",
  },
  {
    id: "beneficiary_a_number",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's A-Number / USCIS Online Account Number",
    question: "Does the beneficiary have an Alien Registration Number (A-Number) or USCIS Online Account Number? If yes, provide it. If not, type 'N/A'.",
    hint: "e.g., A-123456789 or N/A",
    optional: true,
  },
  {
    id: "beneficiary_ssn",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's U.S. Social Security Number (if any)",
    question: "Does the beneficiary have a U.S. Social Security Number? If yes, provide it. If not, type 'N/A'.",
    hint: "XXX-XX-XXXX or N/A",
    optional: true,
  },
  {
    id: "beneficiary_current_status",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Current Nonimmigrant Status (if in the U.S.)",
    question: "If the beneficiary is currently in the United States, what is their current nonimmigrant status? Type 'N/A' if they are outside the U.S.",
    hint: "e.g., H-1B, F-1 OPT, L-1 or N/A",
    optional: true,
  },
  {
    id: "beneficiary_address",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Current Address",
    question: "What is the beneficiary's current address? Include street, apartment number, city, state, and ZIP code.",
    hint: "e.g., 45 Elm Street Apt 2, San Jose, CA 95112",
  },
  {
    id: "beneficiary_phone",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Daytime Telephone Number",
    question: "What is the beneficiary's daytime telephone number?",
    hint: "e.g., (408) 555-1234",
  },
  {
    id: "beneficiary_email",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary's Email Address",
    question: "What is the beneficiary's email address? Type 'N/A' if none.",
    hint: "e.g., ravi@email.com or N/A",
    optional: true,
  },
  {
    id: "beneficiary_is_self_petitioning",
    part: "Part 3",
    partTitle: "Information About the Beneficiary",
    label: "Beneficiary Filing as Self-Petitioner?",
    question: "Is the beneficiary the one filing this petition as a self-petitioner (common for EB-1A or EB-2 NIW)?",
    hint: "Select one",
    options: ["Yes", "No"],
  },

  // ── Part 4: Processing Information ────────────────────────────────────────
  {
    id: "perm_labor_cert_filed",
    part: "Part 4",
    partTitle: "Processing Information",
    label: "Labor Certification (PERM) Filed?",
    question: "Was a labor certification (PERM) filed with the Department of Labor for this position? (This typically applies to EB-2 and EB-3 petitions that are not National Interest Waivers.) If yes, also include the PERM case number.",
    hint: "e.g., Yes, A-12345-67890 or No",
  },
  {
    id: "priority_date",
    part: "Part 4",
    partTitle: "Processing Information",
    label: "Priority Date",
    question: "What is the priority date for this petition? (For PERM cases, this is the date the labor certification was filed. For others, it's usually the date this petition is filed.)",
    hint: "MM/DD/YYYY",
  },
  {
    id: "proffered_wage",
    part: "Part 4",
    partTitle: "Processing Information",
    label: "Wage Offered (Proffered Wage)",
    question: "What is the wage being offered for this position (proffered wage)? Give the annual amount.",
    hint: "e.g., $95,000",
  },
  {
    id: "premium_processing_requested",
    part: "Part 4",
    partTitle: "Processing Information",
    label: "Premium Processing Requested?",
    question: "Is Premium Processing being requested for faster adjudication?",
    hint: "Select one",
    options: ["Yes", "No"],
  },

  // ── Part 6: Basic Information About the Proposed Employment ───────────────
  {
    id: "job_title",
    part: "Part 6",
    partTitle: "Basic Information About the Proposed Employment",
    label: "Job Title",
    question: "Let's describe the job being offered.\n\nWhat is the job title?",
    hint: "e.g., Senior Software Engineer",
  },
  {
    id: "job_duties",
    part: "Part 6",
    partTitle: "Basic Information About the Proposed Employment",
    label: "Job Duties",
    question: "Briefly describe the job duties for this position.",
    hint: "e.g., Design and develop backend systems...",
  },
  {
    id: "job_min_education",
    part: "Part 6",
    partTitle: "Basic Information About the Proposed Employment",
    label: "Minimum Education Required",
    question: "What is the minimum education required for this position?",
    hint: "e.g., Bachelor's degree in Computer Science",
  },
  {
    id: "job_min_experience",
    part: "Part 6",
    partTitle: "Basic Information About the Proposed Employment",
    label: "Minimum Experience Required",
    question: "How many years of experience are required, and in what field? Type 'N/A' if none required.",
    hint: "e.g., 5 years in software development or N/A",
    optional: true,
  },
  {
    id: "job_full_or_part_time",
    part: "Part 6",
    partTitle: "Basic Information About the Proposed Employment",
    label: "Full-Time or Part-Time?",
    question: "Is this a full-time or part-time position? If part-time, include the number of hours per week.",
    hint: "Select one, or e.g., Part-Time, 20 hours/week",
    options: ["Full-Time", "Part-Time"],
  },
];

export const I140_PARTS = [
  { id: "Part 1", title: "Information About the Petitioner" },
  { id: "Part 2", title: "Petition Type" },
  { id: "Part 3", title: "Information About the Beneficiary" },
  { id: "Part 4", title: "Processing Information" },
  { id: "Part 6", title: "Basic Information About the Proposed Employment" },
];
