export interface I485Question {
  id: string;
  part: string;
  partTitle: string;
  label: string;
  question: string;
  hint: string;
  optional?: boolean;
  options?: string[];
}

export const I485_QUESTIONS: I485Question[] = [
  // ── Part 1: Information About You ─────────────────────────────────────────
  {
    id: "other_names_used",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Other Names Used",
    question:
      "Welcome! Let's fill out Form I-485 together — this is the application to become a lawful permanent resident (green card holder) from inside the U.S.\n\nFirst, have you used any other names — a maiden name, nickname, or alias? If yes, list them. If not, type 'None'.",
    hint: "e.g., Maiden name, or None",
    optional: true,
  },
  {
    id: "family_name",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Family Name (Last Name)",
    question: "What is your family name (last name)?",
    hint: "e.g., Sharma",
  },
  {
    id: "given_name",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Given Name (First Name)",
    question: "What is your given name (first name)?",
    hint: "e.g., Ananya",
  },
  {
    id: "middle_name",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Middle Name",
    question: "What is your middle name? (Type 'N/A' if you don't have one)",
    hint: "e.g., Rao or N/A",
    optional: true,
  },
  {
    id: "a_number",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Alien Registration Number (A-Number)",
    question: "Do you have an Alien Registration Number (A-Number)? If yes, provide it. If not, type 'N/A'.",
    hint: "e.g., A-123456789 or N/A",
    optional: true,
  },
  {
    id: "uscis_account_number",
    part: "Part 1",
    partTitle: "Information About You",
    label: "USCIS Online Account Number",
    question: "Do you have a USCIS Online Account Number (from filing other forms online)? If yes, provide it. If not, type 'N/A'.",
    hint: "e.g., 1234567890 or N/A",
    optional: true,
  },
  {
    id: "ssn",
    part: "Part 1",
    partTitle: "Information About You",
    label: "U.S. Social Security Number",
    question: "What is your U.S. Social Security Number, if you have one? Type 'N/A' if you don't have one.",
    hint: "XXX-XX-XXXX or N/A",
    optional: true,
  },
  {
    id: "date_of_birth",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Date of Birth",
    question: "What is your date of birth?",
    hint: "MM/DD/YYYY",
  },
  {
    id: "country_of_birth",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Country of Birth",
    question: "What country were you born in?",
    hint: "e.g., India",
  },
  {
    id: "current_status",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Current Immigration Status",
    question: "What is your current immigration status or nonimmigrant category (as shown on your most recent I-94 or visa)?",
    hint: "e.g., F-1, H-1B, H-4, Asylee",
  },
  {
    id: "i94_number",
    part: "Part 1",
    partTitle: "Information About You",
    label: "I-94 Arrival-Departure Record Number",
    question: "What is your I-94 Arrival-Departure Record Number? (Look it up at i94.cbp.dhs.gov if you don't have the paper stamp.)",
    hint: "e.g., 12345678901",
  },
  {
    id: "date_of_last_arrival",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Date of Last Arrival Into the U.S.",
    question: "What was the date of your last arrival into the United States?",
    hint: "MM/DD/YYYY",
  },
  {
    id: "passport_number",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Passport / Travel Document Number",
    question: "What is your current passport or travel document number?",
    hint: "e.g., N1234567",
  },
  {
    id: "passport_country_expiry",
    part: "Part 1",
    partTitle: "Information About You",
    label: "Passport Country of Issuance and Expiration Date",
    question: "What country issued that passport, and when does it expire? (e.g., 'India, 05/14/2028')",
    hint: "Country, MM/DD/YYYY",
  },

  // ── Part 2: Application Type ──────────────────────────────────────────────
  {
    id: "basis_for_filing",
    part: "Part 2",
    partTitle: "Application Type or Filing Category",
    label: "Basis for Filing",
    question: "What is the basis for your green card application? Select the one that applies:",
    hint: "Select one",
    options: [
      "Immediate relative of a U.S. citizen (spouse, parent, or unmarried child under 21)",
      "Family-based preference category (F1, F2A, F2B, F3, or F4)",
      "Employment-based (approved or concurrently filed Form I-140)",
      "Asylee or refugee (physically present in the U.S. at least 1 year after grant)",
      "Other basis (e.g., VAWA self-petitioner, special immigrant, diversity visa)",
    ],
  },

  // ── Part 3: Additional Information About You ──────────────────────────────
  {
    id: "mailing_street",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Mailing Address – Street",
    question: "Now let's cover some additional details about you.\n\nWhat is your current mailing address — street number and name? Include apartment/suite number if applicable.",
    hint: "e.g., 456 Oak Avenue Apt 2C",
  },
  {
    id: "mailing_city",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Mailing Address – City or Town",
    question: "What city or town?",
    hint: "e.g., San Jose",
  },
  {
    id: "mailing_state",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Mailing Address – State",
    question: "What state?",
    hint: "e.g., CA",
  },
  {
    id: "mailing_zip",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Mailing Address – ZIP Code",
    question: "What is your ZIP code?",
    hint: "e.g., 95112",
  },
  {
    id: "physical_address_same",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Physical Address Same as Mailing?",
    question: "Is your physical (home) address the same as the mailing address you just gave?",
    hint: "Select one",
    options: ["Yes", "No"],
  },
  {
    id: "address_history_5yr",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Address History (Last 5 Years)",
    question: "List every address you've lived at for the last 5 years, most recent first, with the dates at each. If your current address covers the entire 5 years, just say so.",
    hint: "e.g., '456 Oak Ave, San Jose CA, 01/2022–present; 12 Elm St, Austin TX, 06/2019–12/2021'",
  },
  {
    id: "marital_status",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Marital Status",
    question: "What is your current marital status?",
    hint: "Select one",
    options: ["Single", "Married", "Divorced", "Widowed", "Marriage Annulled", "Separated"],
  },
  {
    id: "daytime_phone",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Daytime Telephone Number",
    question: "What is your daytime telephone number?",
    hint: "e.g., (408) 555-1234",
  },
  {
    id: "email",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Email Address",
    question: "What is your email address? (Type 'N/A' if none.)",
    hint: "e.g., ananya@email.com or N/A",
    optional: true,
  },
  {
    id: "father_name_dob",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Father's Full Name and Date of Birth",
    question: "What is your father's full name and date of birth? (Type 'Unknown' if you don't know.)",
    hint: "Full name, MM/DD/YYYY — e.g., 'Raj Kumar Sharma, 03/12/1958'",
  },
  {
    id: "father_birth_country",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Father's Country of Birth",
    question: "What country was your father born in? (Type 'Unknown' if you don't know.)",
    hint: "e.g., India or Unknown",
  },
  {
    id: "mother_name_dob",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Mother's Full Name and Date of Birth",
    question: "What is your mother's full name and date of birth? (Type 'Unknown' if you don't know.)",
    hint: "Full name, MM/DD/YYYY — e.g., 'Sunita Sharma, 07/22/1960'",
  },
  {
    id: "mother_birth_country",
    part: "Part 3",
    partTitle: "Additional Information About You",
    label: "Mother's Country of Birth",
    question: "What country was your mother born in? (Type 'Unknown' if you don't know.)",
    hint: "e.g., India or Unknown",
  },

  // ── Part 8: Background Information ────────────────────────────────────────
  {
    id: "employment_history",
    part: "Part 8",
    partTitle: "Background Information",
    label: "Employment History (Last 5 Years)",
    question:
      "Almost there — just a few background questions.\n\nList your employer(s) for the last 5 years: company name, address, your occupation, and dates of employment (most recent first). If you've had only one job, just describe that one.",
    hint: "e.g., 'Acme Corp, Austin TX, Software Engineer, 06/2021–present'",
  },
  {
    id: "arrests_convictions",
    part: "Part 8",
    partTitle: "Background Information",
    label: "Ever Arrested, Cited, Charged, or Convicted of a Crime?",
    question: "Have you ever been arrested, cited, charged, or convicted of any crime, in the U.S. or any other country?",
    hint: "Answer honestly — a 'Yes' should be reviewed by an immigration attorney before filing.",
    options: ["Yes", "No"],
  },
  {
    id: "removal_proceedings",
    part: "Part 8",
    partTitle: "Background Information",
    label: "Ever in Removal, Deportation, or Exclusion Proceedings?",
    question: "Have you ever been in immigration court (removal, deportation, exclusion, or rescission) proceedings?",
    hint: "A 'Yes' should be reviewed by an immigration attorney before filing.",
    options: ["Yes", "No"],
  },
  {
    id: "claimed_citizenship",
    part: "Part 8",
    partTitle: "Background Information",
    label: "Ever Claimed U.S. Citizenship?",
    question: "Have you ever claimed to be a U.S. citizen, in writing or by voting, in any U.S. federal, state, or local election?",
    hint: "A 'Yes' can be a serious inadmissibility issue — have an attorney review your case first.",
    options: ["Yes", "No"],
  },
  {
    id: "immigration_violations",
    part: "Part 8",
    partTitle: "Background Information",
    label: "Ever Violated Visa Terms or Overstayed?",
    question: "Have you ever violated the terms of a U.S. visa (for example, worked without authorization) or remained in the U.S. beyond your authorized period?",
    hint: "A 'Yes' should be reviewed by an immigration attorney before filing.",
    options: ["Yes", "No"],
  },
];

export const I485_PARTS = [
  { id: "Part 1", title: "Information About You" },
  { id: "Part 2", title: "Application Type or Filing Category" },
  { id: "Part 3", title: "Additional Information About You" },
  { id: "Part 8", title: "Background Information" },
];
