export interface I864Question {
  id: string;
  part: string;
  partTitle: string;
  label: string;
  question: string;
  hint: string;
  optional?: boolean;
  options?: string[];
}

export const I864_QUESTIONS: I864Question[] = [
  // ── Part 1: Basis for Filing ──────────────────────────────────────────────
  {
    id: "basis",
    part: "Part 1",
    partTitle: "Basis for Filing Affidavit of Support",
    label: "Sponsor Type",
    question:
      "Welcome! Let's fill out Form I-864 together.\n\nFirst — why are you filing this affidavit? Select the one that applies:",
    hint: "Select one",
    options: [
      "1a — Petitioner filing for my relative",
      "1b — Filed alien worker petition, related to immigrant",
      "1c — ≥5% ownership in company that filed alien worker petition",
      "1d — I am the only joint sponsor",
      "1e — First of two joint sponsors",
      "1e — Second of two joint sponsors",
      "1f — Original petitioner is deceased; I am substitute sponsor",
    ],
  },

  // ── Part 2: Sponsor Info ──────────────────────────────────────────────────
  {
    id: "sponsor_family_name",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Sponsor's Family Name (Last Name)",
    question: "What is your family name (last name)?",
    hint: "e.g., Smith",
  },
  {
    id: "sponsor_given_name",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Sponsor's Given Name (First Name)",
    question: "What is your given name (first name)?",
    hint: "e.g., John",
  },
  {
    id: "sponsor_middle_name",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Sponsor's Middle Name",
    question: "What is your middle name? (Type 'N/A' if you don't have one)",
    hint: "e.g., Michael or N/A",
    optional: true,
  },
  {
    id: "sponsor_mailing_street",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Mailing Address – Street Number and Name",
    question: "What is your current mailing address — street number and name? Include apartment/suite number if applicable.",
    hint: "e.g., 123 Main Street Apt 4B",
  },
  {
    id: "sponsor_mailing_city",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Mailing Address – City or Town",
    question: "What city or town?",
    hint: "e.g., Houston",
  },
  {
    id: "sponsor_mailing_state",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Mailing Address – State",
    question: "What state?",
    hint: "e.g., TX",
  },
  {
    id: "sponsor_mailing_zip",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Mailing Address – ZIP Code",
    question: "What is your ZIP code?",
    hint: "e.g., 77001",
  },
  {
    id: "sponsor_same_physical",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Physical Address Same as Mailing?",
    question: "Is your physical (home) address the same as the mailing address you just gave?",
    hint: "Select one",
    options: ["Yes", "No"],
  },
  {
    id: "sponsor_domicile_country",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Country of Domicile",
    question: "What is your country of domicile (where you primarily live)?",
    hint: "e.g., United States",
  },
  {
    id: "sponsor_dob",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Date of Birth",
    question: "What is your date of birth?",
    hint: "MM/DD/YYYY",
  },
  {
    id: "sponsor_country_of_birth",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Country of Birth",
    question: "What country were you born in?",
    hint: "e.g., United States, India",
  },
  {
    id: "sponsor_ssn",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "U.S. Social Security Number (Required)",
    question: "What is your U.S. Social Security Number? (Required on the form)",
    hint: "XXX-XX-XXXX",
  },
  {
    id: "sponsor_citizenship",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Immigration Status",
    question:
      "What is your U.S. immigration status?",
    hint: "Select one",
    options: ["U.S. Citizen", "U.S. National", "Lawful Permanent Resident"],
  },
  {
    id: "sponsor_a_number",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Sponsor's A-Number (if any)",
    question: "Do you have an Alien Registration Number (A-Number)? If yes, provide it. If not, type 'N/A'. (Only LPRs typically have one.)",
    hint: "e.g., A-123456789 or N/A",
    optional: true,
  },
  {
    id: "sponsor_military",
    part: "Part 2",
    partTitle: "Information About You (Sponsor)",
    label: "Active Military Duty",
    question: "Are you currently on active duty in the U.S. Armed Forces or U.S. Coast Guard?",
    hint: "Select one",
    options: ["Yes", "No"],
  },

  // ── Part 3: Principal Immigrant ───────────────────────────────────────────
  {
    id: "immigrant_family_name",
    part: "Part 3",
    partTitle: "Information About the Principal Immigrant",
    label: "Immigrant's Family Name (Last Name)",
    question: "Now let's fill in information about the immigrant you're sponsoring.\n\nWhat is the principal immigrant's family name (last name)?",
    hint: "e.g., Patel",
  },
  {
    id: "immigrant_given_name",
    part: "Part 3",
    partTitle: "Information About the Principal Immigrant",
    label: "Immigrant's Given Name (First Name)",
    question: "What is their given name (first name)?",
    hint: "e.g., Priya",
  },
  {
    id: "immigrant_middle_name",
    part: "Part 3",
    partTitle: "Information About the Principal Immigrant",
    label: "Immigrant's Middle Name",
    question: "What is their middle name? (Type 'N/A' if none)",
    hint: "e.g., Kumar or N/A",
    optional: true,
  },
  {
    id: "immigrant_country_of_citizenship",
    part: "Part 3",
    partTitle: "Information About the Principal Immigrant",
    label: "Country of Citizenship or Nationality",
    question: "What is their country of citizenship or nationality?",
    hint: "e.g., India",
  },
  {
    id: "immigrant_dob",
    part: "Part 3",
    partTitle: "Information About the Principal Immigrant",
    label: "Immigrant's Date of Birth",
    question: "What is their date of birth?",
    hint: "MM/DD/YYYY",
  },
  {
    id: "immigrant_a_number",
    part: "Part 3",
    partTitle: "Information About the Principal Immigrant",
    label: "Immigrant's A-Number (if any)",
    question: "Does the immigrant have an Alien Registration Number (A-Number)? If yes, provide it. If not, type 'N/A'.",
    hint: "e.g., A-123456789 or N/A",
    optional: true,
  },
  {
    id: "immigrant_phone",
    part: "Part 3",
    partTitle: "Information About the Principal Immigrant",
    label: "Immigrant's Daytime Telephone Number",
    question: "What is the immigrant's daytime telephone number?",
    hint: "e.g., (713) 555-1234",
  },

  // ── Part 4: Immigrants Being Sponsored ───────────────────────────────────
  {
    id: "sponsoring_principal",
    part: "Part 4",
    partTitle: "Information About the Immigrants You Are Sponsoring",
    label: "Sponsoring Principal Immigrant?",
    question: "Are you sponsoring the principal immigrant named in Part 3?",
    hint: "Select one",
    options: ["Yes", "No"],
  },
  {
    id: "additional_family_members",
    part: "Part 4",
    partTitle: "Information About the Immigrants You Are Sponsoring",
    label: "Additional Family Members",
    question: "Are there any additional family members immigrating at the same time as (or within 6 months of) the principal immigrant that you are also sponsoring?\n\nIf yes, give their names and relationship (e.g., 'Maria Patel, Spouse; Arjun Patel, Son'). If no, type 'None'.",
    hint: "e.g., None, or list names + relationships",
    optional: true,
  },

  // ── Part 5: Household Size ────────────────────────────────────────────────
  {
    id: "household_immigrants_sponsored",
    part: "Part 5",
    partTitle: "Sponsor's Household Size",
    label: "Number of Immigrants Sponsored (this affidavit)",
    question: "Part 5 calculates your household size.\n\nHow many immigrants are you sponsoring on THIS affidavit? (Count the principal immigrant plus any family members listed in Part 4.)",
    hint: "e.g., 1, 2, 3",
  },
  {
    id: "household_spouse",
    part: "Part 5",
    partTitle: "Sponsor's Household Size",
    label: "Spouse (if not already counted)",
    question: "Are you currently married? Enter '1' for your spouse if not already counted above, or '0' if not applicable.",
    hint: "0 or 1",
  },
  {
    id: "household_dependent_children",
    part: "Part 5",
    partTitle: "Sponsor's Household Size",
    label: "Dependent Children (if not already counted)",
    question: "How many dependent children do you have who are NOT already counted above? Enter '0' if none.",
    hint: "e.g., 0, 1, 2",
  },
  {
    id: "household_other_dependents",
    part: "Part 5",
    partTitle: "Sponsor's Household Size",
    label: "Other Dependents (if not already counted)",
    question: "Do you have any other dependents not yet counted? Enter the number, or '0' if none.",
    hint: "e.g., 0, 1",
    optional: true,
  },

  // ── Part 6: Employment and Income ─────────────────────────────────────────
  {
    id: "employment_status",
    part: "Part 6",
    partTitle: "Sponsor's Employment and Income",
    label: "Employment Status",
    question: "What is your current employment status?",
    hint: "Select one",
    options: ["Employed", "Self-Employed", "Retired", "Unemployed"],
  },
  {
    id: "employer_name_1",
    part: "Part 6",
    partTitle: "Sponsor's Employment and Income",
    label: "Name of Employer 1",
    question: "What is your employer's name? (If self-employed, write your business name. If retired/unemployed, type 'N/A'.)",
    hint: "e.g., Google LLC or N/A",
  },
  {
    id: "occupation",
    part: "Part 6",
    partTitle: "Sponsor's Employment and Income",
    label: "Occupation / Job Title",
    question: "What is your occupation or job title?",
    hint: "e.g., Software Engineer",
  },
  {
    id: "annual_income",
    part: "Part 6",
    partTitle: "Sponsor's Employment and Income",
    label: "Current Individual Annual Income",
    question: "What is your current individual annual income (before taxes)?",
    hint: "e.g., $85,000",
  },
  {
    id: "tax_year_1",
    part: "Part 6",
    partTitle: "Sponsor's Employment and Income",
    label: "Most Recent Tax Year & Total Income",
    question: "What was your total income on your most recent Federal tax return? Please give both the tax year and the amount.\n(e.g., '2024, $82,000')",
    hint: "Year, Amount — e.g., 2024, $82,000",
  },
  {
    id: "tax_year_2",
    part: "Part 6",
    partTitle: "Sponsor's Employment and Income",
    label: "2nd Most Recent Tax Year & Total Income",
    question: "What was your total income on your second most recent Federal tax return? (Year and amount, or 'N/A' if not filing for a 2nd year.)",
    hint: "e.g., 2023, $78,000 or N/A",
    optional: true,
  },
  {
    id: "tax_year_3",
    part: "Part 6",
    partTitle: "Sponsor's Employment and Income",
    label: "3rd Most Recent Tax Year & Total Income",
    question: "What about your third most recent Federal tax return? (Year and amount, or 'N/A'.)",
    hint: "e.g., 2022, $75,000 or N/A",
    optional: true,
  },

  // ── Part 8: Contact Info & Signature ──────────────────────────────────────
  {
    id: "sponsor_daytime_phone",
    part: "Part 8",
    partTitle: "Sponsor's Contract, Contact Information, and Signature",
    label: "Sponsor's Daytime Telephone Number",
    question: "Almost done! A few contact details for Part 8.\n\nWhat is your daytime telephone number?",
    hint: "e.g., (713) 555-1234",
  },
  {
    id: "sponsor_mobile_phone",
    part: "Part 8",
    partTitle: "Sponsor's Contract, Contact Information, and Signature",
    label: "Sponsor's Mobile Telephone Number (if any)",
    question: "What is your mobile phone number? (Type 'N/A' if none.)",
    hint: "e.g., (713) 555-9876 or N/A",
    optional: true,
  },
  {
    id: "sponsor_email",
    part: "Part 8",
    partTitle: "Sponsor's Contract, Contact Information, and Signature",
    label: "Sponsor's Email Address (if any)",
    question: "What is your email address? (Type 'N/A' if none.)",
    hint: "e.g., john@email.com or N/A",
    optional: true,
  },
];

export const I864_PARTS = [
  { id: "Part 1", title: "Basis for Filing" },
  { id: "Part 2", title: "Information About You (Sponsor)" },
  { id: "Part 3", title: "Information About the Principal Immigrant" },
  { id: "Part 4", title: "Immigrants You Are Sponsoring" },
  { id: "Part 5", title: "Sponsor's Household Size" },
  { id: "Part 6", title: "Sponsor's Employment and Income" },
  { id: "Part 8", title: "Contact Information and Signature" },
];
