export interface N400Question {
  id: string;
  part: string;
  partTitle: string;
  label: string;
  question: string;
  hint: string;
  optional?: boolean;
  options?: string[];
}

export const N400_PARTS = [
  { id: "Part 1", title: "Basis for Eligibility" },
  { id: "Part 2", title: "Information About You" },
  { id: "Part 3", title: "Accommodations" },
  { id: "Part 4", title: "Addresses & Contact" },
  { id: "Part 5", title: "Marital & Family History" },
  { id: "Part 6", title: "Residence and Employment History" },
  { id: "Part 7", title: "Good Moral Character / Eligibility Questions" },
];

export const N400_QUESTIONS: N400Question[] = [
  // ── Part 1: Basis for Eligibility ───────────────────────────────────────────
  {
    id: "eligibility_basis",
    part: "Part 1",
    partTitle: "Basis for Eligibility",
    label: "Basis for Eligibility",
    question:
      "Welcome! Let's fill out Form N-400 (Application for Naturalization) together.\n\nFirst — which eligibility category applies to you?",
    hint: "Select one",
    options: [
      "5 years as a permanent resident (general provision)",
      "3 years as a permanent resident, married to and living with a U.S. citizen",
      "Permanent resident with qualifying U.S. military service",
      "Other basis (e.g., child of U.S. citizen parent)",
    ],
  },
  {
    id: "lpr_since_date",
    part: "Part 1",
    partTitle: "Basis for Eligibility",
    label: "Date You Became a Permanent Resident",
    question: "What date did you become a lawful permanent resident (the date on your green card)?",
    hint: "e.g., 06/01/2019",
  },

  // ── Part 2: Information About You ───────────────────────────────────────────
  {
    id: "family_name",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Family Name (Last Name)",
    question: "What is your current legal family name (last name), exactly as it appears on your green card?",
    hint: "e.g., Kim",
  },
  {
    id: "given_name",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Given Name (First Name)",
    question: "What is your given name (first name)?",
    hint: "e.g., Jiho",
  },
  {
    id: "middle_name",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Middle Name",
    question: "What is your middle name? (Type 'N/A' if you don't have one)",
    hint: "e.g., Soo or N/A",
    optional: true,
  },
  {
    id: "other_names_used",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Other Names Used",
    question: "Have you used any other names since birth (maiden name, nickname, alias)? List them, or type 'N/A' if none.",
    hint: "e.g., Maiden name: Park or N/A",
    optional: true,
  },
  {
    id: "name_change_requested",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Legal Name Change Requested",
    question: "Would you like to legally change your name as part of this application? If so, what should your new name be? Type 'N/A' if you don't want a name change.",
    hint: "e.g., N/A, or new full name",
    optional: true,
  },
  {
    id: "a_number",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Alien Registration Number (A-Number)",
    question: "What is your A-Number? It starts with 'A' followed by 8 or 9 digits, and appears on your green card or USCIS notices.",
    hint: "e.g., A 123 456 789",
  },
  {
    id: "uscis_online_account_number",
    part: "Part 2",
    partTitle: "Information About You",
    label: "USCIS Online Account Number",
    question: "Do you have a USCIS Online Account Number (from filing forms online)? Type 'N/A' if you don't have one.",
    hint: "e.g., 1234567890 or N/A",
    optional: true,
  },
  {
    id: "ssn",
    part: "Part 2",
    partTitle: "Information About You",
    label: "U.S. Social Security Number",
    question: "What is your U.S. Social Security Number?",
    hint: "e.g., 123-45-6789",
  },
  {
    id: "date_of_birth",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Date of Birth",
    question: "What is your date of birth?",
    hint: "e.g., 03/22/1990",
  },
  {
    id: "place_of_birth",
    part: "Part 2",
    partTitle: "Information About You",
    label: "Place of Birth (City, Country)",
    question: "What city and country were you born in?",
    hint: "e.g., Seoul, South Korea",
  },

  // ── Part 3: Accommodations ──────────────────────────────────────────────────
  {
    id: "disability_accommodation",
    part: "Part 3",
    partTitle: "Accommodations",
    label: "Disability Accommodation Requested",
    question: "Do you need any disability-related accommodations (for example, a sign language interpreter, wheelchair access, or extra time) for your interview and civics test?",
    hint: "Select one",
    options: ["No, I don't need any accommodations", "Yes, I need accommodations"],
    optional: true,
  },

  // ── Part 4: Addresses & Contact ─────────────────────────────────────────────
  {
    id: "mailing_street",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "Mailing Address — Street",
    question: "What is your current mailing address — street number and name? (include Apt/Suite if applicable)",
    hint: "e.g., 45 Maple Ave, Apt 3B",
  },
  {
    id: "mailing_city",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "City",
    question: "What city?",
    hint: "e.g., Fairfax",
  },
  {
    id: "mailing_state",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "State",
    question: "What state? (2-letter code)",
    hint: "e.g., VA",
  },
  {
    id: "mailing_zip",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "ZIP Code",
    question: "What is your ZIP code?",
    hint: "e.g., 22030",
  },
  {
    id: "physical_address_same",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "Physical Address Same as Mailing",
    question: "Is your physical residence the same as the mailing address you just gave?",
    hint: "Select one",
    options: ["Yes, same address", "No, different address"],
  },
  {
    id: "address_history_5yr",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "Address History (Last 5 Years)",
    question: "List any other addresses where you've lived in the last 5 years, with approximate dates for each. Type 'N/A' if you've only lived at your current address.",
    hint: "e.g., 12 Oak St, Boston MA, 2021-2023 or N/A",
    optional: true,
  },
  {
    id: "daytime_phone",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "Daytime Phone",
    question: "What is your daytime phone number?",
    hint: "e.g., (703) 555-0198",
  },
  {
    id: "email",
    part: "Part 4",
    partTitle: "Addresses & Contact",
    label: "Email Address",
    question: "What is your email address?",
    hint: "e.g., jiho@email.com",
  },

  // ── Part 5: Marital & Family History ────────────────────────────────────────
  {
    id: "marital_status",
    part: "Part 5",
    partTitle: "Marital & Family History",
    label: "Current Marital Status",
    question: "What is your current marital status?",
    hint: "Select one",
    options: ["Single, never married", "Married", "Divorced", "Widowed", "Marriage annulled", "Separated"],
  },
  {
    id: "times_married",
    part: "Part 5",
    partTitle: "Marital & Family History",
    label: "Number of Times Married",
    question: "How many times have you been married (including your current marriage, if any)? Type '0' if never married.",
    hint: "e.g., 0, 1, 2",
  },
  {
    id: "spouse_name",
    part: "Part 5",
    partTitle: "Marital & Family History",
    label: "Current Spouse's Full Name",
    question: "If you're currently married, what is your spouse's full name? Type 'N/A' if not applicable.",
    hint: "e.g., Minji Kim or N/A",
    optional: true,
  },
  {
    id: "spouse_citizenship",
    part: "Part 5",
    partTitle: "Marital & Family History",
    label: "Current Spouse's Citizenship",
    question: "What country is your current spouse a citizen of? (Type 'U.S. Citizen' if applicable, or 'N/A' if not married.)",
    hint: "e.g., U.S. Citizen or N/A",
    optional: true,
  },
  {
    id: "number_of_children",
    part: "Part 5",
    partTitle: "Marital & Family History",
    label: "Number of Children",
    question: "How many children do you have (including adult children, and children not living with you)? Type '0' if none.",
    hint: "e.g., 0, 1, 2",
  },

  // ── Part 6: Residence and Employment History ───────────────────────────────
  {
    id: "days_outside_us_5yr",
    part: "Part 6",
    partTitle: "Residence and Employment History",
    label: "Total Days Outside the U.S. (Last 5 Years)",
    question: "Roughly how many total days have you spent outside the United States during the last 5 years? A rough estimate is fine for now — you'll confirm exact trip dates later.",
    hint: "e.g., 45 days",
  },
  {
    id: "current_employer_or_school",
    part: "Part 6",
    partTitle: "Residence and Employment History",
    label: "Current Employer or School",
    question: "What is the name of your current employer or school? Type 'Unemployed' or 'Retired' if neither applies.",
    hint: "e.g., Acme Corp, or George Mason University",
  },
  {
    id: "occupation",
    part: "Part 6",
    partTitle: "Residence and Employment History",
    label: "Occupation",
    question: "What is your current occupation or job title? Type 'N/A' if unemployed or retired.",
    hint: "e.g., Registered Nurse",
    optional: true,
  },
  {
    id: "employment_history_5yr",
    part: "Part 6",
    partTitle: "Residence and Employment History",
    label: "Employment History (Last 5 Years)",
    question: "List your employers or schools for the last 5 years, with approximate dates for each. Type 'N/A' if your current employer covers the whole period.",
    hint: "e.g., Acme Corp, 2021-present; Beta Inc, 2019-2021",
    optional: true,
  },

  // ── Part 7: Good Moral Character / Eligibility Questions ────────────────────
  {
    id: "claimed_us_citizen",
    part: "Part 7",
    partTitle: "Good Moral Character / Eligibility Questions",
    label: "Ever Claimed to Be a U.S. Citizen",
    question: "Have you ever claimed to be a U.S. citizen (in writing or any other way)?",
    hint: "A 'Yes' answer should be reviewed with an immigration attorney before filing — it can affect your eligibility.",
    options: ["No", "Yes"],
  },
  {
    id: "failed_to_file_taxes",
    part: "Part 7",
    partTitle: "Good Moral Character / Eligibility Questions",
    label: "Ever Failed to File Required Taxes",
    question: "Have you ever failed to file a required federal, state, or local tax return?",
    hint: "A 'Yes' answer should be reviewed with an immigration attorney before filing — it can affect your eligibility.",
    options: ["No", "Yes"],
  },
  {
    id: "totalitarian_party_member",
    part: "Part 7",
    partTitle: "Good Moral Character / Eligibility Questions",
    label: "Communist or Totalitarian Party Membership",
    question: "Have you ever been a member of, or in any way associated with, the Communist Party or any other totalitarian party?",
    hint: "A 'Yes' answer should be reviewed with an immigration attorney before filing — it can affect your eligibility.",
    options: ["No", "Yes"],
  },
  {
    id: "arrested_or_convicted",
    part: "Part 7",
    partTitle: "Good Moral Character / Eligibility Questions",
    label: "Ever Arrested, Cited, Charged, or Convicted",
    question: "Have you ever been arrested, cited, charged, convicted, or placed in an alternative sentencing or rehabilitation program for any offense (even if later dismissed, expunged, or pardoned)?",
    hint: "A 'Yes' answer should be reviewed with an immigration attorney before filing — it can affect your eligibility.",
    options: ["No", "Yes"],
  },
  {
    id: "selective_service_registration",
    part: "Part 7",
    partTitle: "Good Moral Character / Eligibility Questions",
    label: "Selective Service Registration",
    question: "Are you male, and if so, did you register with Selective Service between the ages of 18 and 25?",
    hint: "A 'No' (if it applies to you) should be reviewed with an immigration attorney before filing — it can affect your eligibility.",
    options: ["Not applicable (not male, or outside that age range)", "Yes, I registered", "No, I did not register"],
  },
];
